/*
 * File: app/controller/Account.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EduApp.controller.Account', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: 'mainview',
            loginPanel: 'mainview #loginPanel',
            welcomePanel: 'mainview #welcomePanel',
            dirList: '#dirList'
        },

        control: {
            "mainview #showRegisterButton": {
                tap: 'showRegister'
            },
            "mainview #showLoginButton": {
                tap: 'showLogin'
            },
            "loginform #loginButton": {
                tap: 'login'
            },
            "registerform #registerButton": {
                tap: 'register'
            },
            "mainview #dirList": {
                itemtap: 'listSubDir'
            }
        }
    },

    showRegister: function(button, e, eOpts) {

        var registerForm = Ext.create('widget.registerform'),	// Registration form
            mainView = this.getMainView();						// Main view

        // Navigate to register
        mainView.push({
            xtype: "registerform",
            title: "Register"
        });

    },

    showLogin: function(button, e, eOpts) {

        var loginForm = Ext.create('widget.loginform'),	// Login form
            mainView = this.getMainView();				// Main view

        // Navigate to login
        mainView.push({
            xtype: "loginform",
            title: "Login"
        });

    },

    login: function(button, e, eOpts) {
                    var form = button.up('formpanel'),		// Login form
                    values = form.getValues(),				// Form values
                    mainView = this.getMainView(),			// Main view
                    loginPanel = this.getLoginPanel(),		// Login and register buttons
                    welcomePanel = this.getWelcomePanel();	// Welcome panel
        			dirs = this.getDirList();

                    // Success
                    var successCallback = function(res, req) {
                    var json = Ext.decode(res.responseText);
                    console.log('reponse :- ' + res.responseText);
                    if(json.statusCode == '200'){
                        localStorage.setItem('UserAuthorization', json.userApiKey);
                        loadDir();
                        // Go back
                        mainView.pop();

                        // Hide login panel
                        loginPanel.hide();

                        // Show welcome panel
                        welcomePanel.show();
                     }else{
                         Ext.Msg.alert("Authentication failed!\n" + json.moreInfo);
                     }

                };

                // Failure
                var failureCallback = function(resp, ops) {

                    // Show login failure error
                    Ext.Msg.alert("Login Failure", resp);

                };

                function loadDir(){


                    var sto = Ext.create('EduApp.store.DirsStore');
                    var auth = localStorage.getItem('UserAuthorization');
                    console.log("user authorisation : "+auth);
                    sto.load({
                        params:{
                            userAuth:auth,
                        },
                        scope:this,
                        callback: function(records, operation, success){
                            dirs.setStore(sto);
                        }
                    });
                }

                // Login using server-side authentication service
                Ext.Ajax.request({
                    url: "api-1.1/auth",
                    method: 'POST',
                    params: Ext.util.JSON.encode(values),
                    headers:{
                        'Content-Type':'application/json',
                        'X-Application-Name':'add',
                    },
                   //callbackKey: 'callback',
        		  success:  successCallback,
                  failure: failureCallback,
                });
    },

    register: function(button, e, eOpts) {

        var form = button.up('formpanel'),			// Login form
            values = form.getValues(),				// Form values
            mainView = this.getMainView(),			// Main view
            loginPanel = this.getLoginPanel(),		// Login and register buttons
            welcomePanel = this.getWelcomePanel(),	// Welcome panel
            dirs = this.getDirList();


        // Success
        var successCallback = function(res, req) {
            // Success
            var json = Ext.decode(res.responseText);
            console.log('reponse :- ' + res.responseText);
            if(json.statusCode == '200'){
                localStorage.setItem('UserAuthorization', json.userApiKey);
                loadDir();

                // Go back
                mainView.pop();

                // Hide login panel
                loginPanel.hide();

                // Show welcome panel
                welcomePanel.show();
              }else{
                  Ext.Msg.alert("Registration failed!\n" + json.moreInfo);
              }
        };


        // Failure
        var failureCallback = function(resp, ops) {

            // Show login failure error
            Ext.Msg.alert("Registration Failure", resp);

        };


        function loadDir(){
            var sto = Ext.create('EduApp.store.DirsStore');
            var auth = localStorage.getItem('UserAuthorization');
            console.log("user authorisation : "+auth);
            sto.load({
                params:{
                    userAuth:auth,
                },
                scope:this,
                callback: function(records, operation, success){
                    dirs.setStore(sto);
                    }
                });
            }

        // TODO: Register using server-side authentication service
        Ext.Ajax.request({
        		url: "api-1.1/users",
                method: 'POST',
                params: Ext.util.JSON.encode(values),
                headers:{
                    'Content-Type':'application/json',
                    'X-Application-Name':'add',
                },
        		success: successCallback,
        		failure: failureCallback
        });

        // Just run success for now
        // successCallback();
    },

    listSubDir: function(dataview, index, target, record, e, eOpts) {
        var  dirs = this.getDirList();
        console.log("listSubDir tapped...");
        var recorde = dataview.getStore().getAt(index);
        var file = record.get('name');

        var curDir =  record.get('currentDir');
        console.log('Selected item index : '+index);
        console.log('Selected item value: '+ file);

                    var auth = localStorage.getItem('UserAuthorization');

                        loadDir();


                function loadDir(){
                    var sto = Ext.create('EduApp.store.DirsStore');
                    var auth = localStorage.getItem('UserAuthorization');
                    console.log("user authorisation : "+auth);
                    sto.load({
                        params: {
                            userAuth: auth,
                            currentDir: curDir,
                            file: file,
                        },
                        scope:this,
                        callback: function(records, operation, success){
                            dirs.setStore(sto);
                            }
                        });
                    }

    }

});