/*
 * File: app/view/DirectoryBrowser.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EduApp.view.DirectoryBrowser', {
    extend: 'Ext.navigation.View',
    alias: 'widget.directoryBrowser',

    requires: [
        'Ext.tab.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'tabpanel',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'container',
                        title: 'Tab 1',
                        items: [
                            {
                                xtype: 'list',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Tab 2'
                    },
                    {
                        xtype: 'container',
                        title: 'Tab 3'
                    }
                ]
            }
        ]
    }

});