/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EduApp.view.MainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainview',

    requires: [
        'Ext.Panel',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'panel',
                itemId: 'homePanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'panel',
                        hidden: false,
                        itemId: 'loginPanel',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'showLoginButton',
                                margin: 20,
                                padding: 8,
                                text: 'Login'
                            },
                            {
                                xtype: 'button',
                                itemId: 'showRegisterButton',
                                margin: 20,
                                padding: 8,
                                text: 'Register'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        hidden: true,
                        itemId: 'welcomePanel',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'list',
                                hidden: false,
                                itemId: 'dirList',
                                emptyText: '',
                                itemTpl: [
                                    '<div>{imageUrl} {name}</div>'
                                ],
                                store: 'DirsStore'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});