/*
 * File: app/view/RegisterForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EduApp.view.RegisterForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.registerform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.Email',
        'Ext.field.Password'
    ],

    config: {
        items: [
            {
                xtype: 'fieldset',
                title: 'EduApp - Register User',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'First Name',
                        labelWidth: '40%',
                        name: 'firstName',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Last Name',
                        labelWidth: '40%',
                        name: 'lastName'
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Birthday',
                        labelWidth: '40%',
                        name: 'birthday',
                        placeHolder: 'mm/dd/yyyy'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Username',
                        labelWidth: '40%',
                        name: 'userName',
                        required: true
                    },
                    {
                        xtype: 'emailfield',
                        label: 'Email',
                        labelWidth: '40%',
                        name: 'email',
                        required: true,
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'passwordfield',
                        label: 'Password',
                        labelWidth: '40%',
                        name: 'password',
                        required: true
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'registerButton',
                margin: 20,
                padding: 8,
                text: 'Register'
            }
        ]
    }

});